// Configuração — Grupo DEX (24 contas Omie consolidadas)
// Credenciais NÃO ficam aqui — vêm do Sheets (10dCg9c...) baixado em runtime.
module.exports = {
  cliente: {
    nome: "Grupo Demo",
    subdomain: "demo-bi",
    coolify_app_uuid: "ow97qdhlrzakhvz8fxzc4kws",
    cor_primaria: "#22d3ee",
  },

  fontes: {
    adapters: ["omie-multi"],

    omie_multi: {
      sheets_id: "10dCg9cunnS-RSQyOFTPixFpO504H814Q8woTI7w6aRw",
      concurrency: 24,                      // todas as contas em paralelo (rate limit é por App_Key)
      skip: [],                             // contas a pular (nome exato)
      only: [],                             // se preenchido, só essas contas
      cliente_label: "Grupo DEX",
      bancos_ok: [],                        // [] = aceita todos os bancos (não filtra)
    },

    drive: {
      base_path: "G:/Meu Drive/BGP/CLIENTES/BI/454. GRUPO DEX/BASES",
    },
  },

  pages: {
    geral: {
      overview: "active",
      receita: "active",
      despesa: "active",
      fluxo: "active",
      tesouraria: "active",
      comparativo: "active",
      relatorio: "active",       // liberado pro Grupo DEX
      valuation: "active",       // liberado pro Grupo DEX
    },
    outros: {
      orcamento: "active",             // tela de orçamento — análise específica
      lojas: "active",                 // ranking 24 lojas
      risco: "active",                 // HHI / concentração / risco
      indicators: "upsell",            // PRO
      faturamento_produto: "upsell",   // PRO
      curva_abc: "upsell",             // PRO
      marketing: "upsell",             // PRO
      hierarquia: "hidden",
      detalhado: "hidden",
      profunda_cliente: "hidden",
      crm: "hidden",
    },
  },

  meta: {
    categoria_overrides: {
        "Categoria 001": "outros",
        "Categoria 002": "outros",
        "Categoria 003": "outros",
        "Categoria 004": "despesa",
        "Categoria 005": "despesa",
        "Categoria 006": "despesa",
        "Categoria 007": "despesa",
        "Categoria 008": "outros",
        "Categoria 009": "outros",
        "Categoria 010": "outros",
        "Categoria 011": "outros",
        "Categoria 012": "outros",
        "Categoria 013": "despesa",
        "Categoria 014": "despesa",
        "Categoria 015": "despesa",
        "Categoria 016": "outros",
        "Categoria 017": "outros",
        "Categoria 018": "outros",
        "Categoria 019": "outros",
        "Categoria 020": "outros",
        "Categoria 021": "custo",
        "Categoria 022": "custo",
        "Categoria 023": "custo",
        "Categoria 024": "custo",
        "Categoria 025": "custo",
        "Categoria 026": "custo",
        "Categoria 027": "despesa",
        "Categoria 028": "despesa",
        "Categoria 029": "despesa",
        "Categoria 030": "outros",
        "Categoria 031": "outros",
        "Categoria 032": "despesa",
        "Categoria 033": "despesa",
        "Categoria 034": "despesa",
        "Categoria 035": "outros",
        "Categoria 036": "outros",
        "Categoria 037": "outros",
        "Categoria 038": "despesa",
        "Categoria 039": "custo",
        "Categoria 040": "custo",
        "Categoria 041": "custo",
        "Categoria 042": "custo",
        "Categoria 043": "custo",
        "Categoria 044": "outros",
        "Categoria 045": "outros",
        "Categoria 046": "outros",
        "Categoria 047": "outros",
        "Categoria 048": "outros",
        "Categoria 049": "despesa",
        "Categoria 050": "custo",
        "Categoria 051": "despesa",
        "Categoria 052": "custo",
        "Categoria 053": "despesa",
        "Categoria 054": "outros",
        "Categoria 055": "outros",
        "Categoria 056": "outros",
        "Categoria 057": "outros",
        "Categoria 058": "outros",
        "Categoria 059": "despesa",
        "Categoria 060": "despesa",
        "Categoria 061": "despesa",
        "Categoria 062": "despesa",
        "Categoria 063": "despesa",
        "Categoria 064": "despesa",
        "Categoria 065": "despesa",
        "Categoria 066": "despesa",
        "Categoria 067": "despesa",
        "Categoria 068": "despesa",
        "Categoria 069": "despesa",
        "Categoria 070": "despesa",
        "Categoria 071": "despesa",
        "Categoria 072": "despesa",
        "Categoria 073": "despesa",
        "Categoria 074": "outros",
        "Categoria 075": "outros",
        "Categoria 076": "outros",
        "Categoria 077": "outros",
        "Categoria 078": "despesa",
        "Categoria 079": "despesa",
        "Categoria 080": "despesa",
        "Categoria 081": "despesa",
        "Categoria 082": "despesa",
        "Categoria 083": "despesa",
        "Categoria 084": "custo",
        "Categoria 085": "despesa",
        "Categoria 086": "despesa",
        "Categoria 087": "despesa",
        "Categoria 088": "despesa",
        "Categoria 089": "despesa",
        "Categoria 090": "despesa",
        "Categoria 091": "despesa",
        "Categoria 092": "despesa",
        "Categoria 093": "despesa",
        "Categoria 094": "outros",
        "Categoria 095": "outros",
        "Categoria 096": "outros",
        "Categoria 097": "outros",
        "Categoria 098": "despesa",
        "Categoria 099": "despesa",
        "Categoria 100": "outros",
        "Categoria 101": "despesa",
        "Categoria 102": "outros",
        "Categoria 103": "despesa",
        "Categoria 104": "outros",
        "Categoria 105": "outros",
        "Categoria 106": "outros",
        "Categoria 107": "outros",
        "Categoria 108": "outros",
        "Categoria 109": "despesa",
        "Categoria 110": "imposto",
        "Categoria 111": "despesa",
        "Categoria 112": "imposto",
        "Categoria 113": "imposto",
        "Categoria 114": "imposto",
        "Categoria 115": "despesa",
        "Categoria 116": "imposto",
        "Categoria 117": "imposto",
        "Categoria 118": "outros",
        "Categoria 119": "outros",
        "Categoria 120": "outros",
        "Categoria 121": "imposto",
        "Categoria 122": "despesa",
        "Categoria 123": "despesa",
        "Categoria 124": "despesa",
        "Categoria 125": "despesa",
        "Categoria 126": "despesa",
        "Categoria 127": "despesa",
        "Categoria 128": "despesa",
        "Categoria 129": "custo",
        "Categoria 130": "custo",
        "Categoria 131": "outros",
        "Categoria 132": "despesa",
        "Categoria 133": "despesa",
        "Categoria 134": "despesa",
        "Categoria 135": "outros",
        "Categoria 136": "outros",
        "Categoria 137": "outros",
        "Categoria 138": "outros",
        "Categoria 139": "outros",
        "Categoria 140": "custo",
        "Categoria 141": "custo",
        "Categoria 142": "custo",
        "Categoria 143": "outros",
        "Categoria 144": "outros",
        "Categoria 145": "outros",
        "Categoria 146": "despesa",
        "Categoria 147": "despesa",
        "Categoria 148": "despesa",
        "Categoria 149": "despesa",
        "Categoria 150": "despesa",
        "Categoria 151": "despesa",
        "Categoria 152": "despesa",
        "Categoria 153": "despesa",
        "Categoria 154": "despesa",
        "Categoria 155": "despesa",
        "Categoria 156": "despesa",
        "Categoria 157": "despesa",
        "Categoria 158": "despesa",
        "Categoria 159": "despesa",
        "Categoria 160": "despesa",
        "Categoria 161": "despesa",
        "Categoria 162": "despesa",
        "Categoria 163": "despesa",
        "Categoria 164": "despesa",
        "Categoria 165": "despesa",
        "Categoria 166": "despesa",
        "Categoria 167": "despesa",
        "Categoria 168": "despesa",
        "Categoria 169": "despesa",
        "Categoria 170": "custo",
        "Categoria 171": "custo",
        "Categoria 172": "custo"
  },
    ano_corrente: 2026,
    metas_crm: { mes: 1_000_000, ano: 12_000_000 },
    valuation_premissas: { wacc: 25, growth_year2: 20, growth_year3: 20, ipca: 4.5, perpetuity_growth: 10 },
  },

  template: {
    version_when_created: "1.0.0",
    version_last_synced: "1.0.0",
  },
};
